services:
  frontend:
    build:
      context: ./frontend # フロントエンド用のディレクトリ
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c 'cd bloomlily-app && yarn start' # 必要なら修正
    ports:
      - "3001:3000"
    networks:
      - app-network
    env_file:
      - .env

  server:
    build:
      context: ./server # サーバ用のディレクトリ
    volumes:
      - ./server:/usr/src/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
